product: nginx
full_name: NGINX
type: product

benchmark_id: NGINX
benchmark_root: "./guide"

profiles_root: "./profiles"

cpes_root: "../../shared/applicability"
cpes:
  - nginx:
      name: "cpe:/a:f5:nginx"
      title: "NGINX"
      check_id: installed_app_is_nginx

reference_uris:
  cis: 'https://www.cisecurity.org/benchmark/nginx'
